language: bash
os: linux
dist: bionic
addons:
  apt:
    update: true
    packages: [bash, zsh, shellcheck]
jobs:
  include:
    - os: linux
      dist: bionic
      services: docker
before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - curl -fsSL https://git.io/shellspec | sh -s master -y
script:
  - shellcheck -x -a  *.sh && shellcheck -x -a  */*.sh
  - shellspec -s bash 
